---
title: "empirical_project1_memo"
author: "Lindsey Greenhill"
date: "3/7/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggthemes)
library(tidyverse)
library(tidycensus)
library(vtable)
library(statar)
library(RColorBrewer)
library(wesanderson)
library(viridis)
library(stargazer)
library(gt)
library(ggpubr)
library(haven)

atlas <- read_dta("atlas.dta")

# subsetting to CT, fairfield county, 

atlas <- atlas %>%
  mutate(fc = if_else(state == 9 & county == 001, 1, 0),
         ct = if_else(state == 9, 1, 0)) %>%
  mutate(national_rank_education = percent_rank(gsmn_math_g3_2013),
         national_rank_mobility = percent_rank(kfr_pooled_pooled_p25))

fc <- atlas %>%
  filter(state == 9, county == 001)

ct <- atlas %>%
  filter(state == 9)

```

### looking at variables I care about

```{r echo=FALSE}

## distribution of absolute mobility nationally, state, and in FC

US_25 <- atlas %>%
  ggplot(aes(x = kfr_pooled_pooled_p25,
             y = ..density..)) +
  geom_histogram(binwidth = 1,
                 fill = "azure3") +
  geom_vline(xintercept = mean(atlas$kfr_pooled_pooled_p25, na.rm = T)) +
  labs(title = "Distribution of Absolute Mobility \n at the 25th percentile (US)",
       subtitle = "Mean = 42.86") +
  scale_x_continuous(limits = c(0,100)) +
  theme_clean()+
  theme(plot.title = element_text(size = 12)) 

ct_25 <- ct %>%
  ggplot(aes(x = kfr_pooled_pooled_p25,
             y = ..density..)) +
  geom_histogram(binwidth = 1,
                 fill = "azure3") +
  geom_vline(xintercept = mean(ct$kfr_pooled_pooled_p25, na.rm = T)) +
  labs(title = "Distribution ofAbsolute Mobility \n at the 25th percentile (CT)",
       subtitle = "Mean = 44.81") +
  scale_x_continuous(limits = c(0,100)) +
  theme_clean()+
  theme(plot.title = element_text(size = 12)) 

fc_25 <- fc %>%
  ggplot(aes(x = kfr_pooled_pooled_p25,
             y = ..density..)) +
  geom_histogram(binwidth = 1,
                 fill = "azure3") +
  geom_vline(xintercept = mean(fc$kfr_pooled_pooled_p25, na.rm = T)) +
  labs(title = "Distribution of Absolute Mobility \n at the 25th percentile (FC)",
       subtitle = "Mean = 47.79") +
  scale_x_continuous(limits = c(0,100)) +
  theme_clean() +
  theme(plot.title = element_text(size = 12)) 
  


ggarrange(US_25, ct_25, fc_25)


# standard deviations

comparative_sd <- tibble(place = c("Fairfield County",
                                      "CT",
                                      "USA"),
                            sd_kfr_pooled_pooled_p25 = 
                              c(8.15, 7, 7.12)) %>%
  gt() %>%
  tab_header(title = "Standard Deviations: US, CT, FC",
             subtitle = "FC has largest sd")

comparative_sd

  
```


## looking at education now

```{r}

# here we see the national pattern

school_national <- atlas %>%
  ggplot(aes(x = gsmn_math_g3_2013, y = kfr_pooled_pooled_p25)) +
  stat_binmean(n = 20, geom = "point") +
  stat_smooth(method = "lm", se = FALSE) +
  labs(title = "Upward Mobility vs. Third Grade Standardized Tests",
       subtitle = "Mobility is higher is areas with higher scores") +
  theme_clean()


ct_acs <- get_acs(geography = "tract",
              geometry = TRUE,
              state = "CT",
              variables = "B19013_001")

ct_joined <- ct_acs %>%
  mutate(tract = as.double(str_sub(GEOID, start = -6))) %>%
  left_join(ct, by = "tract") %>%
  select(GEOID, county, NAME, tract,gsmn_math_g3_2013, kfr_pooled_pooled_p25,
         national_rank_education, national_rank_mobility) %>%
  filter(county == 1) %>%
  mutate(dot_color = as_factor(case_when(tract == 70300 ~ "Westside, Bridgeport",
                            tract == 35400 ~ "New Canaan",
                            TRUE ~ "other")))

# now going to zoom in to fairfield county

school_fc <- ct_joined %>%
  ggplot(aes(x = gsmn_math_g3_2013, y = kfr_pooled_pooled_p25)) +
  geom_point(aes(col = dot_color)) +
  stat_smooth(method = "lm", se = FALSE) +
  scale_x_continuous(limits = c(.75, 7)) +
  scale_color_manual(values = c("black", "red", "forestgreen")) +
  annotate("text", x = 2.3, y = 25, label = "Westside, Bridgeport",
           col = "red") +
  annotate("text", x = 6.5, y = 66, label = "New Canaan",
           col = "forestgreen") +
 guides(col = FALSE) +
  labs(title = "Absolute mobility p25 vs. 3rd Grade Test Scores") +
  theme_clean()

school_fc

fc_limited <- fc %>%
  select(czname, tract, gsmn_math_g3_2013, kfr_pooled_pooled_p25) %>%
  arrange(gsmn_math_g3_2013) %>%
  head(10) 

# lowest scores are tracts 




pal <- wes_palette("GrandBudapest1", 100, type = "continuous")

ct_joined %>%
  filter(county == 1) %>%
  ggplot(aes(fill = gsmn_math_g3_2013)) +
  geom_sf() +
  scale_fill_viridis(option = "B") +
  labs(title = "Fairfield County 3rd Grade Test Scores") +
  theme_void()

# bridgeport and Danbury have the worst it looks like
```

## regressions

```{r results = "asis"}

mod_1 <- lm(kfr_pooled_pooled_p25 ~ gsmn_math_g3_2013, data = fc)

stargazer(mod_1,
          type = "latex")
```

